apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: smartsplit
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Z2c="
  SPRING_DATASOURCE_PASSWORD: "Z2c="
  APP_JWT_SECRET: "Zjl3dkpmYkExQVpRZUdsYzF4M0I4am9RY1hva2NpOFovazU3UTRFdnU3L2Q3cHFudUttaXlqcUdGTzlSa2pyN3ZtZ2h4YlYrT2I2dlIzazBmLzdlVTdBN3Vod1lXMTg0ODlrbVVVMTRPSll1SWsvRUo5czhBM3A1aGhDVVpTN0JBQXEvbkRqMkd2YWJnYlhDUCtQV21rekVadzk2T25rUlV3RHc5MGRsQTVRMFB3L3hqZ055aEVMU3ByWFBKRDZOalB1OWNTU0VBTFNGckI3bEhaRFFZdExjZW5Zd28zOFlMTkZDYzhQcHAwL1U5U1dtNTEzSER5bnN6TEFrZzViUUQvUzhLanBrTmlDMTZ3bm9zcDE1Uk1WRkcwTGxXZWt1bzRLWllUQzRDS2UyNmI1K0JXcXRMWVhyTXFQbjR5M0xuK2lPS21WMkltYzBNMWJPZktmNGlZSjNrMHViaHcyZXc4dGVKQmpwSHQwPQ="